"use client";

import { useMemo, useState } from "react";
import { ChartNoAxesColumn } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table";
import { experimentEvidence, historyEvents } from "@/lib/experiments";
import type { LabState } from "@/lib/promo";

const title = (s: string) => s.charAt(0).toUpperCase() + s.slice(1);

export default function ResearchPanel({ state, onRefresh }: { state: LabState; onRefresh: () => void }) {
  const [limit, setLimit] = useState(30);
  const evidence = useMemo(() => experimentEvidence(state), [state]);
  const events = useMemo(() => historyEvents(state), [state]);
  return <details className="panel research-panel">
    <summary><ChartNoAxesColumn size={20} aria-hidden="true" />Research plan & full event log<span className="small-note">{state.attempts.length} attempts · {state.candidates.length} generated</span></summary>
    <div className="research-content">
      <div className="panel-heading"><h2>Tier evidence</h2><Button variant="outline" onClick={onRefresh}>Refresh</Button></div>
      <p className="section-copy">One distinct accepted code is one example, even if it was tried repeatedly. Zero fitting rules means the old linear tier hypothesis has been falsified; it does not identify the machine's actual tier logic.</p>
      <Table className="history-table"><TableHeader><TableRow><TableHead>Tier awarded</TableHead><TableHead>Distinct codes</TableHead><TableHead>Fourth-digit formulas still fitting</TableHead></TableRow></TableHeader><TableBody>{evidence.tiers.map(row => <TableRow key={row.tier}><TableCell>{title(row.tier)}</TableCell><TableCell>{row.distinctCodes}</TableCell><TableCell>{row.fittingAffineRules === null ? "No data" : row.fittingAffineRules.toLocaleString()}</TableCell></TableRow>)}</TableBody></Table>
      <p className="prediction-note">The {evidence.tiers.reduce((sum, row) => sum + row.distinctCodes, 0)} distinct accepted codes leave {evidence.checksum.fittingRules.toLocaleString()} affine checksum rule{evidence.checksum.fittingRules === 1 ? "" : "s"} fitting the current evidence. {evidence.checksum.rejectedMatchingBest === null ? "No tested rule fits all accepted codes." : `Even the best fitting rule matches ${evidence.checksum.rejectedMatchingBest} of ${evidence.checksum.distinctRejected} codes rejected without a recorded acceptance.`} A checksum match cannot predict redemption.</p>
      <Table className="history-table"><TableHeader><TableRow><TableHead>Generated by</TableHead><TableHead>Accepted</TableHead><TableHead>Rejected</TableHead><TableHead>Untested</TableHead></TableRow></TableHeader><TableBody>{evidence.cohorts.map(row => <TableRow key={row.rule}><TableCell>Old {title(row.rule)} rule</TableCell><TableCell>{row.accepted}</TableCell><TableCell>{row.rejected}</TableCell><TableCell>{row.untested}</TableCell></TableRow>)}</TableBody></Table>
      <p className="section-copy">Awarded tier disagreed with the generating rule for {evidence.awardedDifferentTier.join(", ") || "no tested candidate"}. Silver code {evidence.silverOnBronzeRule.join(", ") || "—"} fits the old Bronze arithmetic too. These selected tests do not establish a success probability.</p>
      <p className="section-copy">Tagged, distinct first-use codes: backend-issued {evidence.firstUse["backend-issued"].accepted} accepted / {evidence.firstUse["backend-issued"].rejected} rejected; calculated {evidence.firstUse.calculated.accepted} accepted / {evidence.firstUse.calculated.rejected} rejected. Older attempts without this metadata are preserved but excluded from this comparison.</p>
      <h2>Next useful experiment</h2>
      <p className="section-copy">Compare unused backend-issued codes with calculated codes from the same campaign. For each tier, hold back 5 of 10 issued codes to check a rule fitted to the first 5. Record first-use status, issuance source, awarded tier, exact machine response, and campaign. Untagged rejections cannot settle issuance versus reuse. Gold has {evidence.tiers[0].distinctCodes} distinct accepted codes and {evidence.tiers[0].fittingAffineRules ?? "no"} affine fourth-digit rules still fitting them.</p>
      <h2>Full event log</h2>
      <ol className="attempt-list">{events.slice(0, limit).map(event => <li key={event.id}><span className="attempt-number">{event.kind === "generated" ? "+" : event.attempt.outcome === "accepted" ? "✓" : "×"}</span><div><div className="attempt-title"><strong>{event.kind === "attempt" ? title(event.attempt.outcome) : "Generated"} · <code>{event.kind === "attempt" ? event.attempt.code : event.code}</code></strong><span className="small-note">{event.at ? new Date(event.at).toLocaleString() : "Original conversation · date unknown"}</span></div><p>{event.kind === "attempt" ? `${event.attempt.observedTier ? title(event.attempt.observedTier) + " · " : ""}${event.attempt.note || "No machine response recorded."}${event.attempt.testContext ? ` · ${event.attempt.testContext.origin} · ${event.attempt.testContext.use} use${event.attempt.testContext.campaign ? ` · ${event.attempt.testContext.campaign}` : ""}` : ""}` : `${title(event.predictedTier)} arithmetic · not yet tested`}</p></div></li>)}</ol>
      {events.length > limit && <Button variant="outline" onClick={() => setLimit(n => n + 30)}>Show 30 more events</Button>}
    </div>
  </details>;
}
